# Generated by Django 4.2.4 on 2024-01-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0003_rename_company_id_team_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(to='dbase.team'),
        ),
    ]
