# Generated by Django 4.2.4 on 2024-01-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0004_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(through='dbase.Task', to='dbase.project'),
        ),
    ]
