# Generated by Django 4.2.4 on 2024-01-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0006_rename_projects_user_project_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_set',
            field=models.ManyToManyField(to='dbase.team'),
        ),
    ]
