# Generated by Django 4.2.4 on 2024-01-27 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0008_rename_team_set_user_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='team',
            new_name='teams',
        ),
    ]
