# Generated by Django 4.2.4 on 2024-01-27 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0010_project_budget_task_actual_time_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 27, 17, 4, 45, 585617, tzinfo=datetime.timezone.utc)),
        ),
    ]
