# Generated by Django 4.2.4 on 2024-01-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0012_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bill_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
